[project]
name = "dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dotenv>=0.9.9",
    "notebook>=7.4.5",
    "pypdf>=5.9.0",
    "requests>=2.32.4",
]
